### ISSUE TITLE
where is the week objective? ( Tests and pure functions)

### ISSUE THREAD

**Issue by NourAdawi** [GSG-G11/Comfy-Hoody-team1#46]
The main objective of this week and the goal of this project is testing and pure functions,  However, you didn't make a single test!  

ALWAYS, applying week objectives is more important than having the app completed! 

and please make sure to never miss the tests anymore..

**Comment by Fady-Alwazir** [comment]
https://github.com/GSG-G11/Comfy-Hoody-team1/blob/main/test.js
